general {
        colors = true
        interval = 5
        color_good = "#A3BE8C"
        color_degraded = "#EBCB8B"
        color_bad = "#BF616A"
}

order += "wireless _first_"
order += "disk /"
order += "cpu_usage"
order += "memory"
order += "battery all"
order += "tztime local"

wireless _first_ {
        format_up = "WLAN: %essid"
        format_down = "WLAN: down"
}

disk "/" {
        format = "DISK: %avail"
}

cpu_usage {
        format = "CPU: %usage"
}

memory {
        format = "RAM: %used"
        threshold_degraded = "200M"
        threshold_critical = "50M"
}

battery all {
        format = "BAT: %percentage %status"
        status_chr = "[CHR]"
        status_bat = "[BAT]"
        status_full = "[FULL]"
        low_threshold = 15
}

tztime local {
        format = "%d.%m.%Y %H:%M"
}
